apiVersion: v1
kind: ConfigMap
metadata:
  name: devsecops-app-config
  namespace: devsecops-platform
  labels:
    owner: rajamohan
data:
  APP_NAME: "Enterprise DevSecOps Platform"
  AUTHOR: "Rajamohan"
  ENVIRONMENT: "demo"